---
title: "EMDAT Visualizations"
author: "Ram Mukund Kripa"
date: "8/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(here)
library(rnaturalearth)

```

```{r dataget}
brazil_clean <- read_csv(file = here("clean_data","Brazil.csv")) %>%
  select(-c("Latitude","Longitude"))
indsl_clean <- read_csv(file = here("clean_data","India_SriLanka.csv"))%>%
  select(-c("Latitude","Longitude"))
viet_clean <- read_csv(file = here("clean_data","Vietnam.csv"))%>%
  select(-c("Latitude","Longitude"))
dis_types <- c("Flood","Storm","Landslide","Drought")
emdat_hydros <- bind_rows(brazil_clean,indsl_clean,viet_clean) %>%
  filter(`Disaster Type` %in% dis_types)


```

```{r bounds}
bounds <- read_csv(file = here("data","region_boxes_csv.csv"))

in_reg <- function(latitude,longitude,region_name){
  reg <- bounds %>%
    filter(Region == region_name)
  in_box <- (latitude<=reg$Lat_max & latitude>=reg$Lat_min
                    &longitude<=reg$Lng_max & longitude>=reg$Lng_min)
  return(in_box)
}

new_any <- function(vec){
  resy <- NA
  for (i in vec){
    if (is.na(i)){
      
    }
    else if (i==TRUE) {
      return(TRUE)
    }
    else{
      resy <- FALSE
    }
  }
  return(resy)
}
```

# USING LAT LONG BOXES

```{r}
Phil_inbox <- Phil_data %>%
  rowwise() %>%
  mutate(in_the_box = in_reg(lat,long,region),
         `Dis No` = as_factor(`Dis No`),
         `Start Month` = as.numeric(`Start Month`))
```

## Brazil Map
```{r}

braz_map <- ne_countries(country = "Brazil",
                         returnclass = "sf")

read_csv(here("clean_data","with_box_shape","Brazil_Clean.csv")) %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  drop_na(lat) %>%
ggplot()+
  geom_sf(data = braz_map)+
   geom_point(mapping = aes(y = lat, x = long, color = in_the_box))+
  labs(title = "Brazil Map",
       color = "In Lat Long Box")
files <- c("Phil900.csv","Phil900to1800.csv","Phil1800to2700.csv","Phil2700to3600.csv","Phil3600to4500.csv","Phil4500toend.csv")
listy <- list()

for (file_name in files){
  
  listy[[file_name]] <- read_csv(here("clean_data",file_name))
  
}

Phil_data = bind_rows(listy)
Phil_data %>%
  write_csv(here("clean_data","Phil.csv"))



```

```{r}
emdat_inbox %>%
  group_by(`Dis No`) %>%
  summarize(region_name = region, any_in_box = new_any(in_the_box)) %>%
  group_by(region_name, any_in_box) %>%
  summarize(count = n()) %>%
  ggplot(mapping = aes(x = region_name, y = count, fill = any_in_box))+
  geom_col(position = "stack") +
  coord_flip()+
  labs(y = "Region",
       x = "Count",
       fill = "Result",
       title = "Output")
```

```{r}
library(patchwork)

region_plots <- function(file_name){
  tbl_req <- read_csv(here("clean_data","with_box_shape",file_name)) %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  drop_na(lat)
  
diz <- tbl_req %>%
  group_by(`Dis No`) %>%
  summarize(start_month = mean(`Start Month`),
            year = mean(Year),
            any_in_box = new_any(in_reg)) %>%
  mutate(start_month = as_factor(start_month)) %>%
  drop_na(any_in_box)

p1 <- diz %>%
  group_by(any_in_box,start_month) %>%
  summarize(count = n()) %>%
  ggplot(mapping = aes(x = start_month, y = count, fill = any_in_box))+
  geom_col(position = "dodge")

p2 <- diz %>%
  filter(any_in_box == TRUE) %>%
  group_by(year) %>%
  summarize(count = n()) %>%
  ggplot(mapping = aes(x = year, y = count))+
  geom_line()

return(p1+p2+plot_annotation(title = glue::glue("Plots for ",file_name)))
}

region_plots("India_SriLanka_Clean.csv")
  
  
```
## India and Sri Lanka Map

```{r}
library(rgeos)

ind_map <- ne_countries(country = "India",
                          returnclass = "sf")
sl_map <- ne_countries(country = "Sri Lanka",
                          returnclass = "sf")

read_csv(here("clean_data","with_box_shape","India_SriLanka_Clean.csv")) %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  drop_na(lat) %>%
ggplot()+
  geom_sf(data = ind_map)+
  geom_sf(data = sl_map)+
   geom_point(mapping = aes(y = lat, x = long, color = in_reg))+
  labs(title = "Ind/Sl Map",
       color = "In Lat Long Box")
TRUE & FALSE
```

```{r}
region_plots("India_SriLanka")
```


# USING SHAPEFILES

```{r indsl}

library(sf)
north_hem_shap <- st_read(here("shape_data","NH_mask.shp"))
south_hem_shap <- st_read(here("shape_data","SH_mask.shp"))
ggplot()+
  geom_sf(data = ne_countries(returnclass = "sf"), color = "red")+
  geom_sf(data = north_hem_shap, color = "green", fill = "skyblue")+
  geom_sf(data = south_hem_shap, color = "black", fill = "purple")

  
```

## Inside shapefile?

```{r}
library(maptools)
library(rgdal)
library(sp)

sp1 <- readShapeSpatial(here("shape_data","NH_mask.shp"),
                        proj4string = CRS("+init=epsg:25832"))
sp2 <- emdat_inbox %>%
  filter(region == "India_SriLanka") %>%
  drop_na(lat) %>%
  select(lat,long) %>%
  SpatialPoints(proj4string = CRS(proj4string(sp1)))

gContains(sp1,sp2)

```

## Using SF -- Testing

```{r}
points_df <- emdat_inbox %>%
  drop_na(lat) %>%
  head(n= 7L) %>%
  select(lat,long,in_the_box)
points_sf <- st_as_sf(points_df,
                      coords = c("long","lat"),
                      crs = st_crs(south_hem_shap))
a_cont <- st_contains(y = points_sf,
            x = south_hem_shap,
            sparse = FALSE)
ggplot()+
  geom_sf(data = braz_map, color = "green")+
  geom_sf(data = south_hem_shap, color = "black", fill = "purple")+
  geom_sf(data = points_sf, color = "blue")+
  coord_sf(xlim = c(-70, -20), ylim = c(-25, 0))
```

## In shape checking function

```{r}

in_shape <- function(lat,long){
  if (is.na(lat)){
    return(NA)
  }
  if (lat>0){
    x1 <- north_hem_shap
  }
  else {
    x1 <- south_hem_shap
  }
  pointy <- tibble(lat,long) %>%
    st_as_sf(coords = c("long","lat"),
           crs = st_crs(x1))
  conty <- st_contains(y = pointy,
                     x = x1,
                     sparse = FALSE)
  return(conty[1])
}

Phil_boxandshapes <- Phil_inbox %>%
  #filter(region == "Vietnam") %>%
  rowwise() %>%
  mutate(in_shapefile = in_shape(lat,long))
  
Phil_boxandshapes %>%
  ggplot(mapping = aes(x = long, y = lat))
  mutate(equalbox = (in_shapefile==in_the_box)) %>%
  group_by(equalbox) %>%
  summarize(count = n())

viet_boxandshapes %>%
  write_csv(here("clean_data","with_box_shape","Vietnam_Clean.csv"))


```



```{r}
emdat_disasters <- emdat_boxandshapes %>%
  group_by(`Dis No`) %>%
  summarize(any_in_box = new_any(in_the_box),
            any_in_shape = new_any(in_shapefile)) 

emdat_disasters %>%
  pivot_longer(cols = c("any_in_box","any_in_shape"),
               names_to = "Type",
               values_to = "Result") %>%
  #mutate(box_shape = (any_in_box==any_in_shape)) %>%
  group_by(Type,Result) %>%
  summarize(count = n()) %>%
  pivot_wider(names_from = "Result",
              values_from = "count")


```
```{r}
p1 <- emdat_boxandshapes %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  ggplot()+
  geom_sf(data = ne_countries(returnclass = "sf"))+
  geom_point(mapping = aes(x = long, y = lat, color = in_shapefile))
indsl
```
```{r}
p2 <- emdat_boxandshapes %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  ggplot()+
  geom_sf(data = ne_countries(returnclass = "sf"))+
  geom_point(mapping = aes(x = long, y = lat, color = in_reg))
p2
```

```{r}
Phil_map <- ne_countries(country = "Philippines",
                          returnclass = "sf")
Phil_boxandshapes %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  write_csv(here("clean_data","with_box_shape","Phil_clean.csv"))
  
  group_by(`Dis No`) %>%
  summarize(val = new_any(in_reg)) %>%
  group_by(val) %>%
  summarize(count = n())
ggplot()+
  geom_sf(data = Phil_map)+
  geom_point(mapping = aes(x = long, y = lat, color = in_reg))
```

```{r}
viet_boxandshapes %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  group_by(`Dis No`) %>%
  summarize(in_regg = new_any(in_reg)) %>%
  group_by(in_regg) %>%
  summarize(count = n())
phil1
ggplot()+
  geom_sf(data = Phil_map, color = "green")+
  geom_sf(data = north_hem_shap, color = "black", fill = "purple")+
  xlim(110, 130)+
  ylim(0,25)
```
```{r}
phil1 <- read_csv(here("clean_data","Phil900.csv"))
phil2 <- read_csv(here("clean_data","Phil900to1800.csv"))
phil3 <- read_csv(here("clean_data","Phil1800to2700.csv"))
phil_map <- ne_countries(country = "Philippines",
                          returnclass = "sf")
  ggplot() +
     geom_sf(data = phil_map)+
  geom_point(data = phil1, mapping = aes(x = long, y = lat, color = "blue"))+
    geom_point(data = phil2, mapping = aes(x = long, y = lat, color = "blue"))+
    geom_point(data = phil3, mapping = aes(x = long, y = lat, color = "blue"))
 

```