---
title: "EMDAT Analysis"
author: "Ram Mukund Kripa"
date: "12/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
library(tidyverse)
library(sf)
library(here)
library(weed)
```

## Loading In the Data

```{r}

emdat_dat <- read_csv(here("clean_data","with_box_shape","Full_Clean.csv"))
glimpse(emdat_dat)
new_any <- function(vec){
  resy <- NA
  for (i in vec){
    if (is.na(i)){
      
    }
    else if (i==TRUE) {
      return(TRUE)
    }
    else{
      resy <- FALSE
    }
  }
  return(resy)
}
```

## Analysis

### NAs at the Location Level

```{r}

emdat_dat %>%
  weed::percent_located_locations(lat_column = "lat",
                                  lng_column = "long",
                                  plot_result = FALSE)

```

### NAs at the Disaster level

```{r}

emdat_dat %>%
  weed::percent_located_disasters(lat_column = "lat", 
                                  lng_column = "long",
                                  plot_result = FALSE)

```

## Using "EFFECTIVE MONTH" to counter southern hemisphere

```{r}
emdat_dat %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_reg = new_any(in_reg), start_month_eff = first(start_month_effective)) %>%
  group_by(any_in_reg, start_month_eff) %>%
  summarize(count = n()) %>%
  ggplot(mapping = aes(x = start_month_eff, y = count, fill = any_in_reg))+
  geom_col(position = "dodge")
  
```
### Effective Month and Locations per year

```{r}
emdat_dat %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_reg = new_any(in_reg), start_month_eff = first(start_month_effective), year = first(Year), reg = first(region)) %>%
  filter(start_month_eff > 9) %>%
  filter(any_in_reg == TRUE) %>%
  group_by(reg, year) %>%
  summarize(count = n()) %>%
  filter(year > 1975) %>%
  #filter(reg == "India_SriLanka" | reg == "Phil") %>%
  ggplot(mapping = aes(x = year, y = count, color = reg)) +
  geom_point()+
  geom_line()
```

```{r}
emdat_dat %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_reg = new_any(in_reg), start_month_eff = first(start_month_effective), year = first(Year), reg = first(region)) %>%
  filter(start_month_eff > 8) %>%
  filter(any_in_reg == TRUE) %>%
  group_by(reg, year) %>%
  summarize(count = n()) %>%
  pivot_wider(id_cols = "year", names_from = "reg", values_from = "count") %>%
  ggplot(mapping = aes(x = India_SriLanka, y = Phil)) +
  geom_point()+
  geom_smooth(method = "lm")+
  ggtitle("Phillipines Vs. India_SriLanka")
```

# Without Filling NAs with 0

```{r}
emdat_dat %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  filter(!`Disaster Type` == "Drought") %>%
  filter(!`Disaster Type` == "Extreme temperature") %>%
  filter(!`Disaster Type` == "Wildfire") %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_reg = new_any(in_reg), start_month_eff = first(start_month_effective), year = first(Year), reg = first(region)) %>%
  filter(start_month_eff > 8) %>%
  filter(any_in_reg == TRUE) %>%
  group_by(reg, year) %>%
  summarize(count = n())

```

```{r}
seasonal_means <- read_csv(here("clean_data", "seasonal_means_pivoted.csv"))
autumn_disasters_yearly <- emdat_dat %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  filter(!`Disaster Type` == "Drought") %>%
  filter(!`Disaster Type` == "Extreme temperature") %>%
  filter(!`Disaster Type` == "Wildfire") %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_reg = new_any(in_reg), start_month_eff = first(start_month_effective), year = first(Year), reg = first(region)) %>%
  filter(start_month_eff > 8) %>%
  filter(any_in_reg == TRUE) %>%
  group_by(reg, year) %>%
  summarize(count = n())
  
autumn_disasters_yearly %>%
  left_join(y = seasonal_means, by = c("year" = "year_no",
                                        "reg" = "region")) %>% 
  ggplot(mapping = aes(x = seasonal_rain, y = count)) +
  geom_point() +
  geom_smooth(method = "lm")+
  ggpubr::stat_cor()
  

```

```{r}
autumn_disasters_yearly %>%
  left_join(y = seasonal_means, by = c("year" = "year_no",
                                        "reg" = "region")) %>% 
  filter(year > 1970) %>%
  ggplot(mapping = aes(x = seasonal_rain, y = count, color = reg)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  facet_wrap(~reg, scales = "free")
```

## What if we fill nas with 0

```{r}
autumn_disasters_yearly %>%
  full_join(y = seasonal_means, by = c("year" = "year_no",
                                        "reg" = "region")) %>% 
  filter(year > 1970) %>%
  mutate(count2 = replace_na(count, 0)) %>%
  ggplot(mapping = aes(x = seasonal_rain, y = count2, color = reg, alpha = 0.2)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, show.legend = TRUE) +
  ggpubr::stat_cor()+
  facet_wrap(~reg, scales = "free")

```

## Dry Disasters

```{r}

autumn_dry_disasters_yearly <- emdat_dat %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  filter(`Disaster Type` %in% c("Drought", "Extreme temperature", "Wildfire")) %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_reg = new_any(in_reg), start_month_eff = first(start_month_effective), year = first(Year), reg = first(region)) %>%
  #filter(start_month_eff > 8) %>%
  filter(any_in_reg == TRUE) %>%
  group_by(reg, year) %>%
  summarize(count = n())


```

```{r}
autumn_dry_disasters_yearly %>%
  full_join(y = seasonal_means, by = c("year" = "year_no",
                                        "reg" = "region")) %>% 
  filter(year > 1970) %>%
  mutate(dis_count2 = replace_na(count, 0)) %>%
  ggplot(mapping = aes(x = seasonal_rain, y = dis_count2, color = reg)) +
  geom_point() + 
  geom_smooth(method = "lm", se = TRUE, show.legend = TRUE) +
  facet_wrap(~reg)+
  #ggpubr::stat_cor()+
  ylab("Dry Disaster Count")
```

##What about dry and wet?
```{r}
autumn_disasters_yearly %>%
  left_join(autumn_dry_disasters_yearly, by = c("year", "reg"), suffix = c("wet","dry")) %>%
  mutate(countdry = replace_na(countdry, 0)) %>%
  ggplot(mapping = aes(x = countwet, y = countdry))+
  geom_point()+
  geom_smooth()+
  facet_wrap(~reg)


```

```{r}
autumn_disasters_yearly %>%
  left_join(autumn_dry_disasters_yearly, by = c("year", "reg"), suffix = c("wet","dry")) %>%
  mutate(countdry = replace_na(countdry, 0)) %>%
  mutate(wetminusdry = countwet - countdry) %>%
  full_join(y = seasonal_means, by = c("year" = "year_no",
                                        "reg" = "region")) %>% 
  filter(year > 1970) %>%
  mutate(wetminusdry = replace_na(wetminusdry, 0)) %>%
  ggplot(mapping = aes(x = seasonal_rain, y = wetminusdry, color = reg)) +
  geom_point() + 
  geom_smooth(method = "lm", se = TRUE, show.legend = TRUE) +
  facet_wrap(~reg, scales = "free")+
  #ggpubr::stat_cor()+
  ylab("Wet - Dry Disaster Count")


```

```{r}
autumn_disasters_yearly %>%
  left_join(autumn_dry_disasters_yearly, by = c("year", "reg"), suffix = c("wet","dry")) %>%
  mutate(countdry = replace_na(countdry, 0)) %>%
  mutate(wetminusdry = countwet - countdry) %>%
  full_join(y = seasonal_means, by = c("year" = "year_no",
                                        "reg" = "region")) %>% 
  filter(year > 1970) %>%
  mutate(wetminusdry = replace_na(wetminusdry, 0)) %>%
  group_by(reg) %>%
  summarize(corrwd = cor(wetminusdry, seasonal_rain, "pairwise.complete.obs"), 
            corrw = cor(countwet, seasonal_rain, "pairwise.complete.obs"))
```
## ENSO?
```{r}
enso_data <- read_csv(here("data","enso_data.csv"))
autumn_wet_disasters_enso <- emdat_dat %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  filter(!`Disaster Type` == "Drought") %>%
  filter(!`Disaster Type` == "Extreme temperature") %>%
  filter(!`Disaster Type` == "Wildfire") %>%
  mutate(south_hem = lat < 0) %>%
  mutate(south_hem = as.numeric(south_hem)) %>%
  mutate(start_month_effective = `Start Month` + (6 * (south_hem))) %>%
  mutate(start_month_effective = start_month_effective %% 12) %>%
  mutate(start_month_effective = replace(start_month_effective, start_month_effective == 0, 12)) %>%
  filter(start_month_effective > 8) %>%
  filter(in_reg = TRUE) %>%
  full_join(enso_data, by = c("Year" = "Year", "Start Month" = "MonthNum")) %>%
  rename("enso_Value" = "Value") 
```

```{r}
autumn_wet_disasters_enso %>%
  filter(is.na(start_month_effective))

```
# With 0s
```{r}
autumn_wet_disasters_enso %>%
  filter(Year > 1950) %>%
  group_by(Year, `Start Month`) %>%
  summarize(enso_value = mean(enso_Value), num_disasters = n_distinct(`Dis No`, na.rm = TRUE)) %>%
  filter(!is.na(enso_value)) %>%
  ggplot(mapping = aes(x = enso_value, y = num_disasters)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  ggpubr::stat_cor() +
  ggtitle("Number of monthly disasters in autumn period Vs ONI for the month")
  
```

# At the season level

```{r}
autumn_wet_disasters_enso %>%
  filter(Year > 1950) %>%
  group_by(Year) %>%
  summarize(enso_value = mean(enso_Value), num_disasters = n_distinct(`Dis No`, na.rm = TRUE)) %>%
  filter(!is.na(enso_value)) %>%
  ggplot(mapping = aes(x = enso_value, y = num_disasters)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  ggpubr::stat_cor() +
  ggtitle("Number of disasters in autumn period Vs Mean ONI for the autumn months")
```

# For each region

```{r}
autumn_wet_disasters_enso %>%
  filter(Year > 1950) %>%
  group_by(region, Year) %>%
  summarize(enso_value = mean(enso_Value), num_disasters = n_distinct(`Dis No`, na.rm = TRUE)) %>%
  filter(!is.na(enso_value), !is.na(region)) %>%
  ggplot(mapping = aes(x = enso_value, y = num_disasters, color = region)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  facet_wrap(~region) +
  ggtitle("Number of disasters in autumn period Vs Mean ONI [For Each region]") 
```

# A cool Map

```{r}
world_map <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
autumn_wet_disasters_enso %>%
  filter(Year > 1950, !is.na(enso_Value)) %>%
  filter(in_reg = TRUE, start_month_effective > 8) %>%
  ggplot() +
  geom_sf(data = world_map) +
  geom_point(mapping = aes(x = long, y = lat, color = enso_Value)) +
  ggtitle("Map of enso values and disaster locations") +
  
```