---
title: "EMDAT disasters"
author: "Ram Mukund Kripa"
date: `r lubridate::today()`
output: github_document
---
## Setup:

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

```

## Packages:

```{r packages}

library(tidyverse)
library(here)
library(gganimate)
library(readxl)

```

## Reading the data:

```{r readdata}
read_emdat <- function(stringy_path){
  read_excel(path = stringy_path,
             skip = 6,
             col_names = TRUE)
}
files <- list.files(path = here("data"),
                    pattern = ".xlsx")
files <- c("Vietnam.xlsx","Phil.xlsx")
listy <- list()

for (file_name in files){
  
  file_name_trimmed <- tools::file_path_sans_ext(basename(file_name))
  
  listy[[file_name_trimmed]] <- read_emdat(here("data",file_name))
  
}

emdat_dirty <- bind_rows(listy,.id = "region")
glimpse(emdat_dirty)
emdat_dirty %>%
  mutate(coords_exist = !is.na(Latitude)) %>%
  group_by(coords_exist) %>%
  summarize(count = n()) %>%
  knitr::kable()
```

## Tidying The Data as Given

```{r cleaning}
emdat_clean <- emdat_dirty %>%
  drop_na(Location) %>%
  filter(`Disaster Subgroup` %in% c("Meteorological",
                                    "Climatological",
                                    "Hydrological")) %>%
  mutate(Latitude = as.numeric(Latitude),
         Longitude = as.numeric(Longitude),
         Year = as.numeric(Year),
         `Start Month` = as_factor(`Start Month`)
         ) %>%
  drop_na(`Start Month`) 
emdat_clean

```

## A Function to obtain the Lat and Long of the top three results for a place

```{r latlongfunc}

library(geonames)
library(countrycode)
## cached
cache_list = list()
get_lat_long <- function(location_name,country_name){
  if (location_name %in% names(cache_list)){
    return(cache_list[[location_name]])
  }
  country_code <- countrycode(sourcevar = country_name,
                              origin = "country.name",
                              destination = "iso2c")
  options(geonamesUsername = "rammkripa")
  return_list <- GNsearch(q = location_name,
                          country = country_code,
                          type = "json"
                          )
  return_val <- tryCatch(
    expr = {
      return_df <- return_list %>%
      select(toponymName,lat,lng) %>%
      head(n = 1L) %>%
      mutate(lat = as.numeric(lat),lng = as.numeric(lng))
      list("lat" = return_df$lat,"long" = return_df$lng)
    },
  error = function(e)
  {
    list("lat" = NA,
         "long" = NA)
  }
  )
  cache_list[[location_name]] <- return_val
  return(return_val)
}
## Testing Logic
pondi_results <- get_lat_long("Pondicherry","India")
pondi_results

  
```

## Function to check if places in a list are in the box specified

```{r funcinbox}

### Writing a function to check if a list of places has at least one location whose lat long is in the box
### Function should call get_lat_long
### first load bounds
bounds <- read_csv(here("data","region_boxes_csv.csv"))

is_in_box <- function(locations,country_name,region_name){
  locations_spl <- stringr::str_split(locations,pattern=", ")[[1]]
  results <- list()
  for (loc in locations_spl){
    reg <- bounds %>%
      filter(Region == region_name)
    results[[loc]] <- tryCatch(
      {
        loc_df <- get_lat_long(loc,country_name) %>%
                  mutate(in_box = (lat<=reg$Lat_max & lat>=reg$Lat_min
                    &lng<=reg$Lng_max & lng>=reg$Lng_min))
        #results[[loc]] <-
        any(loc_df$in_box)
      },
      error = function(e){
        NA
      }
    )
  }
  return(results)
}

## Testing
is_in_box(locations = "Pondicherry, Tamil Nadu, Rajasthan",
          country_name = "India",
          region_name = "India_SriLanka")


```

## Filtering places that are in the box of interest

```{r cleaningfinal}
my_any <- function(listy){
  rez <- NA
  for(i in seq_along(listy)){
    val = listy[[i]]
    if (is.na(val)){
      stringy <- "dummy"
    }
    else if (val == TRUE){
      return(TRUE)
    }
    else if (val == FALSE ) {
      rez <- FALSE
    }
  }
  return(rez)
}

clean_func <- function(listE){
  
    result <- tryCatch(
      {my_any(is_in_box(listE[[1]],
                listE[[2]],
                listE[[3]]))},
      error = function(e){
        e
      }
                )
 
   return(result)   
}
# Testing clean_func

list("Location" = "Pondicherry, Tamil Nadu, Jaipur",
     "Country" = "India",
     "region" = "India_SriLanka")%>%
clean_func()

```

## Testing my_any
```{r}
any(FALSE,NA,"error","blahblah")
xl <- list("x" = FALSE,
           "y" = NA,
           "z" = "err")
my_any(xl)
```

## Cleaning Brazil data (a test)

```{r}

brazil_dat <- emdat_clean %>%
  filter(region == "Brazil")

brazil_dat$in_region <- brazil_dat %>%
  select(Location,Country,region) %>%
  apply(1,clean_func)

brazil_dat %>%
  summarize(perc_NA = mean(is.na(in_region)))

brazil_dat %>%
  drop_na(in_region) %>%
  ggplot(mapping = aes(x = `Start Month`,fill = in_region))+
  geom_bar(stat = "count", position = "dodge")+
  labs(y = "Number of Disasters",
       title = "No of Disasters by Start Month",
       fill = "In Region of Interest")

```

```{r}
brazil_dat %>%
  filter(is.na(in_region)) %>%
  select(Location,in_region)
```

### New Cleaning strategy

```{r}
library(tidytext)
viet_dirty <- emdat_clean %>%
  filter(region == "Vietnam")

dummy_words <- c(
                 "cities","states","provinces","districts","municipalities","regions",
                 "city","state","province","district","municipality","region",
                 "near","-")

viet_clean_top_900 <- viet_dirty %>%
  unnest_tokens(output = "location_word",
                input = Location, 
                token = stringr::str_split,
                pattern = ",|\\(|\\)|;") %>%
  mutate(location_word = str_remove(
    string = location_word, 
    pattern = str_c(dummy_words,collapse="|")))%>%
  filter(!str_detect(location_word, "^[0-9]*$")) %>%
  filter(location_word!=" ") %>%
  head(n = 900L) %>%
  mutate(location_data = purrr::pmap(list(location_word, Country), get_lat_long))

viet_clean_top_900 %>%
  unnest_wider(col = location_data) %>%
  write_csv(here("clean_data","Vietnam1.csv"))

in_reg <- function(latitude,longitude,region_name){
  reg <- bounds %>%
    filter(Region == region_name)
  in_box <- (latitude<=reg$Lat_max & latitude>=reg$Lat_min
                    &longitude<=reg$Lng_max & longitude>=reg$Lng_min)
  return(in_box)
}

new_any <- function(vec){
  resy <- NA
  for (i in vec){
    if (is.na(i)){
      
    }
    else if (i==TRUE) {
      return(TRUE)
    }
    else{
      resy <- FALSE
    }
  }
  return(resy)
}
  
brazil_clean %>%
  rowwise() %>%
  mutate(in_the_box = in_reg(location_data,region),
         `Dis No` = as_factor(`Dis No`),
         `Start Month` = as.numeric(`Start Month`)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_box = new_any(in_the_box),
            start_month = mean(`Start Month`),
            start_year = mean(Year)) %>%
  drop_na(any_in_box) %>%
  mutate(start_month = as_factor(start_month)) %>%
  ggplot(mapping = aes(x = start_month, fill = any_in_box))+
  geom_bar(stat = "count",
           position = "dodge")
  
brazil_clean %>%
  rowwise() %>%
  mutate(in_the_box = in_reg(location_data,region),
         `Dis No` = as_factor(`Dis No`),
         `Start Month` = as.numeric(`Start Month`)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_box = new_any(in_the_box),
            start_month = mean(`Start Month`),
            start_year = mean(Year)) %>%
  group_by(any_in_box) %>%
  summarize(count = n())



```

```{r}
indsl_dirty <- read_emdat(here("data","India_SriLanka.xlsx"))%>%
  mutate(region = "India_SriLanka") 


indsl_loc_dat_1 <- indsl_dirty %>%
  filter(!is.na(`Start Month`)) %>%
  unnest_tokens(output = "location_word",
                input = Location, 
                token = stringr::str_split,
                pattern = ",|\\(|\\)|;|\\/|\\+|\\&|and") %>%
  mutate(location_word = str_remove(
    string = location_word, 
    pattern = str_c(dummy_words,collapse="|")))%>%
  filter(!str_detect(location_word, "^[0-9]*$")) %>%
  filter(location_word!=" ") %>%
  mutate(location_word = stringr::str_trim(location_word)) %>%
  select(Country,location_word) %>%
  unique() %>%
  head(n=999L) %>%
  mutate(location_data = purrr::pmap(list(location_word, Country), get_lat_long))

indsl_loc_dat_2 <- indsl_dirty %>%
  filter(!is.na(`Start Month`)) %>%
  unnest_tokens(output = "location_word",
                input = Location, 
                token = stringr::str_split,
                pattern = ",|\\(|\\)|;|\\/|\\+|\\&|and") %>%
  mutate(location_word = str_remove(
    string = location_word, 
    pattern = str_c(dummy_words,collapse="|")))%>%
  filter(!str_detect(location_word, "^[0-9]*$")) %>%
  filter(location_word!=" ") %>%
  mutate(location_word = stringr::str_trim(location_word)) %>%
  select(Country,location_word) %>%
  unique() %>%
  tail(n=115L) %>%
  mutate(location_data = purrr::pmap(list(location_word, Country), get_lat_long))

indsl_loc_dat <- bind_rows(indsl_loc_dat_1,
                           indsl_loc_dat_2) %>%
  unique() %>%
  unnest_wider(location_data)

indsl_cleany <- indsl_dirty %>%
  filter(!is.na(`Start Month`)) %>%
  unnest_tokens(output = "location_word",
                input = Location, 
                token = stringr::str_split,
                pattern = ",|\\(|\\)|;|\\/|\\+|\\&|and") %>%
  mutate(location_word = str_remove(
    string = location_word, 
    pattern = str_c(dummy_words,collapse="|")))%>%
  filter(!str_detect(location_word, "^[0-9]*$")) %>%
  filter(location_word!=" ") %>%
  mutate(location_word = stringr::str_trim(location_word)) %>%
  left_join(indsl_loc_dat)
  
indsl_cleany %>%
  rowwise() %>%
  mutate(in_the_box = in_reg(lat,long,region),
         `Dis No` = as_factor(`Dis No`),
         `Start Month` = as.numeric(`Start Month`)) %>%
  group_by(`Dis No`) %>%
  summarize(any_in_box = new_any(in_the_box),
            start_month = mean(`Start Month`),
            start_year = mean(Year)) %>%
  group_by(any_in_box) %>%
  summarize(count = n())


  
indsl_cleany %>%
  write_csv(here("clean_data","India_SriLanka.csv"))
  

```




## Session info

```{r, echo = TRUE}
devtools::session_info()
```