---
title: "EMDAT disasters: India and Sri Lanka"
author: "Ram Mukund Kripa"
date: `r lubridate::today()`
output: github_document
---
## Setup:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

```

## Packages:

```{r packages}
library(tidyverse)
library(here)
library(gganimate)
library(readxl)
```

## Reading the data:

```{r readdata}
file <- here("emdat_public_2020_07_21_query_uid-DkRLtJ.xlsx")
sind_tbl <- read_excel(path = file,
                       skip = 6,
                       col_names = TRUE)
head(sind_tbl)
```

## Cleaning Up & Plotting

```{r cleaningplotting}
sind_tbl %>%
  drop_na(Location) %>%
  filter(`Disaster Subgroup` %in% c("Meteorological",
                                    "Climatological",
                                    "Hydrological")) %>%
  mutate(Latitude = as.numeric(Latitude),
         Longitude = as.numeric(Longitude),
         Year = as.numeric(Year),
         `Start Month` = as_factor(`Start Month`)
         ) %>%
  # filtering either by latitude, location or Sri Lanka
  filter((Latitude<14 & Longitude>78) | 
           (stringr::str_detect(string = Location,
        pattern = c("Madras","Chennai","Pondicherry","Tanjore","Tamil Nadu")
        ))
        | (Country=="Sri Lanka" & 
             (stringr::str_detect(string = Location,
                                  pattern = c("East"))))) %>%
  drop_na(`Start Month`) %>%
  group_by(`Start Month`,Country) %>%
  summarize(count = n()) %>%
  ggplot(mapping = aes(x = `Start Month`,
                       y = count))+
  geom_col(fill = "skyblue")+
  labs(x = "Month",
       y = "Number of Disasters",
       title = "Disasters in South India/ SL by month")

```
## Session info

```{r, echo = TRUE}
devtools::session_info()
```