---
title: "RegionPlots"
author: "Ram Mukund Kripa"
date: "12/07/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(tidyverse)
library(patchwork)
library(tidytext)
library(here)
new_any <- function(vec){
  resy <- NA
  for (i in vec){
    if (is.na(i)){
      
    }
    else if (i==TRUE) {
      return(TRUE)
    }
    else{
      resy <- FALSE
    }
  }
  return(resy)
}
region_plots <- function(file_name){
  tbl_req <- read_csv(here("clean_data","with_box_shape",file_name)) %>%
  mutate(in_reg = in_the_box & in_shapefile) %>%
  drop_na(lat)
  
diz <- tbl_req %>%
  group_by(`Dis No`) %>%
  summarize(start_month = mean(`Start Month`),
            year = mean(Year),
            any_in_box = new_any(in_reg),
            type = first(`Disaster Type`)) %>%
  mutate(start_month = as_factor(start_month)) %>%
  drop_na(any_in_box)

p1 <- diz %>%
  group_by(any_in_box,start_month) %>%
  summarize(disaster_count = n()) %>%
  ggplot(mapping = aes(x = start_month, y = disaster_count, fill = any_in_box))+
  geom_col(position = "dodge")

p2 <- diz %>%
  filter(any_in_box == TRUE) %>%
  group_by(year) %>%
  summarize(disaster_count = n()) %>%
  ggplot(mapping = aes(x = year, y = disaster_count))+
  geom_point()+
  geom_line(color = "blue")

p3 <- diz %>%
  filter(any_in_box == TRUE) %>%
  group_by(type) %>%
  summarize(disaster_count = n()) %>%
  ggplot(mapping = aes(x = type, y = disaster_count)) +
  geom_col()+
  coord_flip()

p4 <- diz %>%
  filter(any_in_box == TRUE) %>%
  group_by(start_month,type) %>%
  summarize(disaster_count = n()) %>%
  ggplot(mapping = aes(x = start_month, y = disaster_count, fill = type))+
  geom_col(position = "dodge")
  
  

return((p1+ p2)/(p3 + p4)+plot_annotation(title = glue::glue("Plots for ",file_name)))
# Disaster Type / How many disasters --> p3
}


```

# Brazil

```{r}
region_plots("Brazil_Clean.csv")
```

# South Asia

```{r}
region_plots("India_SriLanka_Clean.csv")
```

# Vietnam

```{r}
region_plots("Vietnam_Clean.csv")
```

# Philippines

```{r}
region_plots("Phil_Clean.csv")
```

# Kenya Tanzania

```{r}
region_plots("Tanzania_Kenya_Clean.csv")
```

# Venezuela Colombia

```{r}
region_plots("Venezuela_Colombia_Clean.csv")
```

# Malaysia Singapore Thailand

```{r}
region_plots("Malaysia_Singapore_Thai_Clean.csv")
```

# Central America

```{r}
region_plots("Central_America_Clean.csv")
```